name: icon_file
description: A Flutter widget to display file icons with extensions.
version: 0.0.1
homepage: https://github.com/Ahmedha91/icon_file
repository: https://github.com/Ahmedha91/icon_file
issue_tracker: https://github.com/Ahmedha91/icon_file/issues

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/file.svg
